name = "DeepLib"
uuid = "ee80fb23-2a65-44b8-b9a2-842548d7201c"
authors = ["banachtech <balaji@banach.tech> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
